/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.util.LinkedList;
import modelo.Course;
import modelo.Subject;
import modelo.Teacher;
import controlador.ControladorCourse;
import controlador.ControladorSubject;
import controlador.ControladorSubjectByCourse;
import controlador.ControladorTeacher;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author wild.chamo
 */
public class AsignarCurso extends javax.swing.JFrame {

    LinkedList<Subject> listas;
    LinkedList<Course> listaco;
    LinkedList<Teacher> listat;

    /**
     * Creates new form AsignarCurso
     */
    public AsignarCurso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        asignaturaBox = new javax.swing.JComboBox<>();
        profesorBox = new javax.swing.JComboBox<>();
        cursosBox = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        asignaturaBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asignaturaBoxActionPerformed(evt);
            }
        });

        jButton1.setText("Realizar asignación");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Asignatura");

        jLabel2.setText("Curso");

        jLabel3.setText("Profesor");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Asignar Curso");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(132, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(143, 143, 143))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(asignaturaBox, 0, 134, Short.MAX_VALUE)
                            .addComponent(profesorBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cursosBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(asignaturaBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(profesorBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cursosBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void asignaturaBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asignaturaBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_asignaturaBoxActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        ControladorSubject objcs = new ControladorSubject();

        listas = objcs.consultarAsignaturas();
        if (!listas.isEmpty()) {
            for (int i = 0; i < listas.size(); i++) {
                Subject asignatura = listas.get(i);
                asignaturaBox.addItem(asignatura.getNameSub());

            }
        }

        ControladorTeacher objct = new ControladorTeacher();
        listat = objct.consultarProfesores();
        if (!listat.isEmpty()) {
            for (int i = 0; i < listat.size(); i++) {
                Teacher profesor = listat.get(i);
                profesorBox.addItem(profesor.getName1T());
            }
        }
        ControladorCourse controladorCo = new ControladorCourse();

        listaco = controladorCo.consultarCursos();
        if (!listaco.isEmpty()) {
            for (int i = 0; i < listaco.size(); i++) {
                Course curso = listaco.get(i);
                cursosBox.addItem(curso.getNameC());

            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String asignatura = String.valueOf(asignaturaBox.getSelectedItem());
        int ids = 0;
        for (int i = 0; i < listas.size(); i++) {
            Subject asignatura1 = listas.get(i);
            if (asignatura.equals(asignatura1.getNameSub())) {
                ids = asignatura1.getSubjectID();

            }
        }

        String curso = String.valueOf(cursosBox.getSelectedItem());
        int idc = 0;
        for (int i = 0; i < listaco.size(); i++) {
            Course curso1 = listaco.get(i);
            if (curso.equals(curso1.getNameC())) {
                idc = curso1.getCourseID();

            }
        }

        String profesor = String.valueOf(profesorBox.getSelectedItem());
        int idt = 0;
        for (int i = 0; i < listat.size(); i++) {
            Teacher profe1 = listat.get(i);
            if (profesor.equals(profe1.getName1T())) {
                idt = profe1.getTeacherID();

            }
        }

        System.out.println(ids);
        System.out.println(idc);
        System.out.println(idt);
        ControladorSubjectByCourse cbc = new ControladorSubjectByCourse();
        if (cbc.asignarMateriaCurso(ids, idc, idt)) {
            JOptionPane.showMessageDialog(null, "Asignación de curso Exitosa");
        } else {
            JOptionPane.showMessageDialog(null, "Asignación de curso Fallida");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AsignarCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AsignarCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AsignarCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AsignarCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AsignarCurso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> asignaturaBox;
    private javax.swing.JComboBox<String> cursosBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox<String> profesorBox;
    // End of variables declaration//GEN-END:variables
}
