/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author usuario
 */
public class OpcionesModificar extends javax.swing.JFrame {

    /**
     * Creates new form OpcionesModificar
     */
    public OpcionesModificar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Ciudadbtn = new javax.swing.JButton();
        Estudiantebtn = new javax.swing.JButton();
        Regresarbtn = new javax.swing.JButton();
        Generobtn = new javax.swing.JButton();
        Asignaturabtn = new javax.swing.JButton();
        Cursobtn = new javax.swing.JButton();
        Profesorbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("¿Qué desea modificar?");

        Ciudadbtn.setText("Ciudad");
        Ciudadbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CiudadbtnActionPerformed(evt);
            }
        });

        Estudiantebtn.setText("Estudiante");
        Estudiantebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstudiantebtnActionPerformed(evt);
            }
        });

        Regresarbtn.setText("Regresar");
        Regresarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarbtnActionPerformed(evt);
            }
        });

        Generobtn.setText("Género");
        Generobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerobtnActionPerformed(evt);
            }
        });

        Asignaturabtn.setText("Asignatura");
        Asignaturabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AsignaturabtnActionPerformed(evt);
            }
        });

        Cursobtn.setText("Curso");
        Cursobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CursobtnActionPerformed(evt);
            }
        });

        Profesorbtn.setText("Profesor");
        Profesorbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfesorbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(Regresarbtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Generobtn, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Profesorbtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Cursobtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Asignaturabtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Estudiantebtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Ciudadbtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Asignaturabtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Cursobtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Profesorbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Estudiantebtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Ciudadbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Generobtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(Regresarbtn)
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegresarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarbtnActionPerformed
Opciones objAlfa = new Opciones (); 
       objAlfa.setVisible(true);
       this.setVisible(false);                // TODO add your handling code here:
    }//GEN-LAST:event_RegresarbtnActionPerformed

    private void CiudadbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CiudadbtnActionPerformed
      ModificarCiudad objAlfa = new ModificarCiudad (); 
       objAlfa.setVisible(true);
       this.setVisible(false);  // TODO add your handling code here:
    }//GEN-LAST:event_CiudadbtnActionPerformed

    private void AsignaturabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AsignaturabtnActionPerformed
ModificarSubject objAlfa = new ModificarSubject (); 
       objAlfa.setVisible(true);
       this.setVisible(false);         // TODO add your handling code here:
    }//GEN-LAST:event_AsignaturabtnActionPerformed

    private void ProfesorbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfesorbtnActionPerformed
ModificarProfesor objAlfa = new ModificarProfesor (); 
       objAlfa.setVisible(true);
       this.setVisible(false);         // TODO add your handling code here:
    }//GEN-LAST:event_ProfesorbtnActionPerformed

    private void CursobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CursobtnActionPerformed
ModificarCourse objAlfa = new ModificarCourse (); 
       objAlfa.setVisible(true);
       this.setVisible(false);         // TODO add your handling code here:
    }//GEN-LAST:event_CursobtnActionPerformed

    private void EstudiantebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstudiantebtnActionPerformed
ModificarEstudiante objAlfa = new ModificarEstudiante (); 
       objAlfa.setVisible(true);
       this.setVisible(false);         // TODO add your handling code here:
    }//GEN-LAST:event_EstudiantebtnActionPerformed

    private void GenerobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerobtnActionPerformed
ModificarGender objAlfa = new ModificarGender (); 
       objAlfa.setVisible(true);
       this.setVisible(false);         // TODO add your handling code here:
    }//GEN-LAST:event_GenerobtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OpcionesModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OpcionesModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OpcionesModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OpcionesModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OpcionesModificar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Asignaturabtn;
    private javax.swing.JButton Ciudadbtn;
    private javax.swing.JButton Cursobtn;
    private javax.swing.JButton Estudiantebtn;
    private javax.swing.JButton Generobtn;
    private javax.swing.JButton Profesorbtn;
    private javax.swing.JButton Regresarbtn;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
